language: python
python:
  - '3.6'

install:
  - pip install -r enqueue/requirements.txt
  - pip install coveralls

script: coverage run -m unittest discover -s tests/

after_success:
  - coveralls

env:
  global:
    - PYTHONDONTWRITEBYTECODE=true
