language: python
# See available versions at https://docs.travis-ci.com/user/languages/python/
python:
  - '3.6'
#  - '3.7-dev' # rq fails

install:
  - pip install -r enqueue/requirements.txt
  - pip install coveralls

script: PYTHONPATH="enqueue/" coverage run -m unittest discover -s tests/

after_success:
  - coveralls

env:
  global:
    - PYTHONDONTWRITEBYTECODE=true
