---
version: "3"
services:
  proxy:
    image: "nginx:latest"
    volumes:
      - ./proxyConf/nginx.conf:/etc/nginx/conf.d/mysite.template:ro
    ports:
      - "${LISTEN_IP:-127.0.0.1}:8080:80"
    environment:
      - ALLOWED_IPS=${ALLOWED_IPS:-0.0.0.0/0}
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - processqueue
      - enqueue
  processqueue:
    build: ./processQueue
    depends_on:
      - enqueue
      - redis
  enqueue:
    build: ./enqueue
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
